# Replace with the name which you want to give to your EKS cluster
# Cluster name can have only lowercase alphanumeric characters and hyphens
# For example: "digit-demo"
cluster_name: "digit-demo"

# Name you want to give to your Database
# DB name must contain only alphanumeric characters
db_name: "digitdb"

# Replace with DB username you want
# DB user name must contain only alphanumeric characters
db_username: "digituser" 

# Replace with Domain name you want for your web applications
domain_name: "quantumappsstore.com"

# Replace with the name you want to give to your S3 bucket which is used to store the terraform state
terraform_state_bucket_name: "digit-terraform-state-bucket"

public_ssh_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCpaS4XVoZqnjo61TsmN3CjXYC6vFXcZDKsMCWtQmikK9VxpmB2lctIsglwNW21mjsbgud9FawYGBg7GYZ10KlZHDsRO6kP9Evbx3UeIuHSDkKMbND816swwp8tU9QihaltUeI9mznhijr+HLZc7H5oy/cIKHvQxNQbLEXXDSfstjI6CU5ZduccsWbqoTRkEViYVn4VeKnYc3ggb23H2AP7cXGAqEUpFRnSE8vLEDbkJdPfaV2kgkQumVoFuY15ohh97kbDuQcwS+QCYbM4szZ38Cojjo2myIxUy0QSEha37Js2ONatFddm+jdp1d+HoHCj71m1JrLBiB8Xulqrjwbf"

tenant_id: "statea"
